#[path = "e2e/complex_query_workflow.rs"]
pub mod complex_query_workflow;
#[path = "e2e/export_workflow.rs"]
pub mod export_workflow;
#[path = "e2e/health_workflow.rs"]
pub mod health_workflow;
#[path = "e2e/helper.rs"]
pub mod helper;
#[path = "e2e/hot_update.rs"]
pub mod hot_update;
#[path = "e2e/index.rs"]
pub mod index;
#[path = "e2e/multi_project_workflow.rs"]
pub mod multi_project_workflow;
#[path = "e2e/plugin_workflow.rs"]
pub mod plugin_workflow;
#[path = "e2e/query_pipeline_workflow.rs"]
pub mod query_pipeline_workflow;
#[path = "e2e/query_workflow.rs"]
pub mod query_workflow;
#[path = "e2e/rerank_workflow.rs"]
pub mod rerank_workflow;
#[path = "e2e/tools_workflow.rs"]
pub mod tools_workflow;
